networks:
  my-network:
    driver: overlay
    attachable: true


services:
  postgres-db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my-network
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "deploy_user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  crud-app:
    image: ddosl/crud-app:latest
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: configtree:/run/secrets/
    secrets:
      - postgres_user
      - postgres_password
    networks:
      - my-network
    depends_on:
      - postgres-db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == manager]

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - my-network
    depends_on:
      - crud-app
    deploy:
      placement:
        constraints: [node.role == manager]
    configs:
      - source: nginx-conf
        target: /etc/nginx/conf.d/default.conf

volumes:
  pg_data:
secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
configs:
  nginx-conf:
    external: true
